### PR TITLE
converting_to_testthat_v3

### PR DESCRIPTION
**Pull request by MowahidLatif**
Converting to testthat version 3

Please wait until confirmation of merger. Waiting for proper checks to pass. Referencing previous errors with current errors for proper diagnoses of issue.

### CODE REVIEW

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Review by aylapear — COMMENTED** [review]
This part is correct but all the warnings need to be corrected. I will close this pull request until one with the appropriate changes as has been pushed.

**Comment by aylapear** [comment]
Create a new pull request when all the warnings are completed

**Pull request closed without merging**
